### ISSUE TITLE
 Do you mind adding your app to F-Droid?

### ISSUE THREAD

**Issue by Artem13327** [nuclearfog/Apollo-Music#12]

**Comment by nuclearfog** [comment]
It would be good. I'll open a request

**Comment by nuclearfog** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2491

**Comment by nuclearfog** [comment]
https://gitlab.com/fdroid/rfp/-/issues/2491

**Comment by gargamel17** [comment]
It is done

**Comment by shuvashish76** [comment]
I see it's tagged as `ready` but still pending for a long time. Since izzy is not active maintainer of F-Droid (see [here](https://gitlab.com/fdroid/admin/-/issues/447)) someone needs to create a merge request. @nuclearfog why not you try it yourself? Here are the [instructions](https://gitlab.com/fdroid/fdroiddata/blob/master/CONTRIBUTING.md#merge-requests).

**Comment by nuclearfog** [comment]
Thank you for the information. I've created a merge request: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/14803

**Comment by nuclearfog** [comment]
the pull request is merged
